// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // 마이그레이션/CLI는 direct 연결 사용 (PgBouncer 미경유). 런타임은 src/lib/prisma.ts 어댑터가 pooled DATABASE_URL 사용.
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
});
