// 글 주제 분류 (ADR-0008) — 무료 규칙 기반 멀티라벨.
// 제목 + 요약 + 피드 <category> 태그를 합친 텍스트를 주제별 키워드 사전에 매칭.
// 영어 토큰은 단어 경계 매칭(ai가 main에 안 걸리게), 한글은 부분 문자열 매칭.

/** 주제 키 → 키워드(한/영, 소문자) */
const TOPIC_KEYWORDS: Record<string, string[]> = {
  frontend: [
    'frontend',
    'front-end',
    '프론트',
    '프론트엔드',
    'react',
    'reactjs',
    'vue',
    'svelte',
    'angular',
    'next.js',
    'nextjs',
    'nuxt',
    'remix',
    'css',
    'scss',
    'tailwind',
    'html',
    'dom',
    'browser',
    '브라우저',
    'webpack',
    'vite',
    'storybook',
    'jsx',
    'spa',
    'ssr',
    'csr',
    '컴포넌트',
    'component',
    '디자인시스템',
    'design-system',
    '접근성',
    'accessibility',
    '렌더링',
    'rendering',
    'ui',
    'ux',
    'web',
    '웹',
    'webview',
    'pwa',
  ],
  backend: [
    'backend',
    'back-end',
    '백엔드',
    '서버',
    'server',
    'spring',
    'springboot',
    'kotlin',
    'java',
    'node.js',
    'nodejs',
    'nestjs',
    'express',
    'django',
    'fastapi',
    'rails',
    'go',
    'golang',
    'api',
    'rest',
    'grpc',
    'graphql',
    'msa',
    'microservice',
    '마이크로서비스',
    'kafka',
    'rabbitmq',
    'redis',
    'mysql',
    'postgresql',
    'postgres',
    'mongodb',
    'rdb',
    'dba',
    'sql',
    'orm',
    'jpa',
    'eda',
    'sse',
    '트랜잭션',
    'transaction',
    '동시성',
    'concurrency',
    '캐시',
    'cache',
    '큐',
    'queue',
    'oauth',
    'jwt',
    '도메인',
    'ddd',
  ],
  infra: [
    'infra',
    'infrastructure',
    '인프라',
    'devops',
    '데브옵스',
    'kubernetes',
    'k8s',
    '쿠버네티스',
    'docker',
    'container',
    '컨테이너',
    'terraform',
    'ansible',
    'aws',
    'gcp',
    'azure',
    'cloud',
    '클라우드',
    'ci/cd',
    'ci-cd',
    'cicd',
    'jenkins',
    'github-actions',
    '배포',
    'deploy',
    'deployment',
    'helm',
    'istio',
    'service-mesh',
    'observability',
    '모니터링',
    'monitoring',
    'prometheus',
    'grafana',
    'sre',
    'scaling',
    '오토스케일',
    'nginx',
    '네트워크',
    'network',
    'serverless',
    '서버리스',
  ],
  mobile: [
    'ios',
    'android',
    '안드로이드',
    '아이폰',
    'swift',
    'swiftui',
    'objective-c',
    'flutter',
    'dart',
    'react-native',
    '리액트네이티브',
    '모바일',
    'mobile',
    '앱',
    'unity',
    'arkit',
    'jetpack',
    'compose',
    'xcode',
    'kotlin-multiplatform',
    'kmp',
    'ar',
    'vr',
  ],
  ai: [
    'ai',
    'ml',
    'machine-learning',
    '머신러닝',
    'deep-learning',
    '딥러닝',
    'llm',
    'gpt',
    'claude',
    'rag',
    'agent',
    '에이전트',
    'agentic',
    '인공지능',
    '모델',
    'model',
    'vlm',
    'embedding',
    '임베딩',
    'transformer',
    'neural',
    '신경망',
    'nlp',
    'recommendation',
    '추천',
    'prompt',
    '프롬프트',
    'fine-tuning',
    '파인튜닝',
    'mlops',
    'vector',
    '벡터',
    'generative',
    '생성형',
    'openai',
    '챗봇',
    'chatbot',
    'diffusion',
  ],
  data: [
    'data',
    '데이터',
    'data-engineering',
    '데이터엔지니어링',
    'analytics',
    '분석',
    'bigquery',
    'spark',
    'hadoop',
    'airflow',
    'etl',
    'elt',
    'warehouse',
    '웨어하우스',
    'dbt',
    'snowflake',
    '파이프라인',
    'pipeline',
    'datalake',
    'lake',
    '집계',
    'bi',
    'dashboard',
    '대시보드',
    'clickhouse',
    'druid',
    'flink',
    'kafka-streams',
    '실시간분석',
  ],
  qa: [
    'qa',
    'test',
    'testing',
    '테스트',
    'e2e',
    '단위테스트',
    'unit-test',
    'integration-test',
    'automation',
    '자동화',
    'cypress',
    'playwright',
    'jest',
    'vitest',
    '품질',
    'quality',
    'tdd',
    '회귀',
    'regression',
    '모킹',
    'mock',
    'junit',
  ],
  security: [
    'security',
    '보안',
    '취약점',
    'vulnerability',
    '암호',
    '암호화',
    'encryption',
    'cryptography',
    'post-quantum',
    '양자내성',
    '인증서',
    'certificate',
    'ssl',
    'tls',
    'xss',
    'csrf',
    'sql-injection',
    '해킹',
    'hacking',
    '인가',
    'authorization',
    '인증',
    'auth',
    '개인정보',
    'privacy',
    'owasp',
    '침해',
    'threat',
  ],
};

/** 한 글에 부여할 주제 최대 개수 (과다 태깅 방지 — 키워드 히트 많은 순) */
const MAX_TOPICS = 3;

/** 고정 주제 키 목록 (탭/필터 기준 순서). 미매칭은 'etc'. */
export const TOPIC_KEYS = Object.keys(TOPIC_KEYWORDS);

const HANGUL = /[㄰-㆏가-힣]/;

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function hasKeyword(haystack: string, keyword: string): boolean {
  if (HANGUL.test(keyword)) return haystack.includes(keyword); // 한글: 부분 문자열
  // 영어/기호: 단어 경계 매칭 (앞뒤가 영숫자가 아니어야 함)
  const re = new RegExp(`(^|[^a-z0-9])${escapeRegExp(keyword)}([^a-z0-9]|$)`);
  return re.test(haystack);
}

/**
 * 제목/요약/피드태그로부터 주제 멀티라벨을 산출. 매칭 없으면 ['etc'].
 */
export function classifyTopics(input: {
  title?: string | null;
  summary?: string | null;
  categories?: string[] | null;
}): string[] {
  const haystack = [input.title, input.summary, ...(input.categories ?? [])]
    .filter(Boolean)
    .join(' ')
    .toLowerCase();

  if (!haystack.trim()) return ['etc'];

  // 주제별 키워드 히트 수로 점수화 → 히트 많은 상위 MAX_TOPICS만 (약한 단일 매칭 노이즈 억제)
  const scored = TOPIC_KEYS.map((topic) => ({
    topic,
    score: TOPIC_KEYWORDS[topic].filter((kw) => hasKeyword(haystack, kw)).length,
  }))
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score);

  if (scored.length === 0) return ['etc'];
  return scored.slice(0, MAX_TOPICS).map((s) => s.topic);
}
